# Site settings
title: Kangfengde
email: kangfengde962@163.com
description: 康凤德的博客 Java Developer
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  kfd9
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
